name: Test Release
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    # See https://goreleaser.com/ci/actions/#signing
    -
      name: Import GPG key
      id: import_gpg
      uses: crazy-max/ghaction-import-gpg@v2
      env:
        # See https://github.com/crazy-max/ghaction-import-gpg#prerequisites
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
        PASSPHRASE: ${{ secrets.PASSPHRASE }}

    - name: Build
      run: make release/test
